### ISSUE TITLE
Building Heekscnc on Ubuntu14.04

### ISSUE THREAD

**Issue by tkatsuki** [jieter/linuxcnc-config#1]
Hi Jan Pieter,
I am trying to install HeeksCAD and HeeksCNC on Ubuntu 14.04 and having some trouble. It seems that the problem is in the version of OCE to be used. Would you mind elaborating how you installed OCE (and what version) when you built HeeksCNC? I'd appreciate your help.
Takeo

**Comment by jieter** [comment]
Don't remember installing any special stuff. This is what's installed on my machine:

```
$ dpkg -l liboce*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                             Version               Architecture          Description
+++-================================-=====================-=====================-======================================================================
ii  liboce-foundation-dev:amd64      0.15-4                amd64                 OpenCASCADE Community Edition CAE platform library development files
rc  liboce-foundation6:amd64         0.12-3                amd64                 OpenCASCADE Community Edition CAE platform shared library
ii  liboce-foundation8:amd64         0.15-4                amd64                 OpenCASCADE Community Edition CAE platform shared library
ii  liboce-modeling-dev:amd64        0.15-4                amd64                 OpenCASCADE Community Edition CAE platform library development files
rc  liboce-modeling6:amd64           0.12-3                amd64                 OpenCASCADE Community Edition CAE platform shared library
ii  liboce-modeling8:amd64           0.15-4                amd64                 OpenCASCADE Community Edition CAE platform shared library
ii  liboce-ocaf-dev:amd64            0.15-4                amd64                 OpenCASCADE Community Edition CAE platform library development files
ii  liboce-ocaf-lite-dev:amd64       0.15-4                amd64                 OpenCASCADE Community Edition CAE platform library development files
rc  liboce-ocaf-lite6:amd64          0.12-3                amd64                 OpenCASCADE Community Edition CAE platform shared library
ii  liboce-ocaf-lite8:amd64          0.15-4                amd64                 OpenCASCADE Community Edition CAE platform shared library
rc  liboce-ocaf6:amd64               0.12-3                amd64                 OpenCASCADE Community Edition CAE platform shared library
ii  liboce-ocaf8:amd64               0.15-4                amd64                 OpenCASCADE Community Edition CAE platform shared library
ii  liboce-visualization-dev:amd64   0.15-4                amd64                 OpenCASCADE Community Edition CAE platform library development files
rc  liboce-visualization6:amd64      0.12-3                amd64                 OpenCASCADE Community Edition CAE platform shared library
ii  liboce-visualization8:amd64      0.15-4                amd64                 OpenCASCADE Community Edition CAE platform shared library
```

**Comment by jieter** [comment]
Do you get any error messages?

**Comment by tkatsuki** [comment]
Mine looks like this:

```
$ dpkg -l liboce*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture   Description
+++-==================-==============-==============-==========================================
ii  liboce-foundation- 0.15-4         amd64          OpenCASCADE Community Edition CAE platform
ii  liboce-foundation8 0.15-4         amd64          OpenCASCADE Community Edition CAE platform
ii  liboce-modeling-de 0.15-4         amd64          OpenCASCADE Community Edition CAE platform
ii  liboce-modeling8:a 0.15-4         amd64          OpenCASCADE Community Edition CAE platform
ii  liboce-ocaf-lite-d 0.15-4         amd64          OpenCASCADE Community Edition CAE platform
ii  liboce-ocaf-lite8: 0.15-4         amd64          OpenCASCADE Community Edition CAE platform
ii  liboce-visualizati 0.15-4         amd64          OpenCASCADE Community Edition CAE platform
ii  liboce-visualizati 0.15-4         amd64          OpenCASCADE Community Edition CAE platform
```

I first followed http://pythonocc.wordpress.com/2013/03/04/installing-on-ubuntu-12-04/ and ran the following commends:

```
sudo apt-get install git
sudo apt-get install build-essential
sudo apt-get install python-dev
sudo apt-get install libxmu-dev libxi-dev
sudo apt-get install tcl-dev
sudo apt-get install tk
sudo apt-get install tk-dev
sudo apt-get install swig
sudo apt-get install cmake
sudo apt-get install ftgl-dev
sudo apt-get install libtbb2
sudo apt-get install libtbb-dev
sudo apt-get install python-fontforge
cd $HOME/gitroot
mkdir oceBuild && cd oceBuild
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/  -DOCE_INSTALL_PREFIX:PATH=/usr/ -DOCE_WITH_FREEIMAGE=OFF  -DOCE_WITH_GL2PS=OFF  -DOCE_VISUALISATION=ON  -DOCE_DATAEXCHANGE=ON  -DOCE_MULTITHREAD_LIBRARY=TBB -DCMAKE_BUILD_TYPE=Release  -DOCE_TESTING:BOOL=ON  ../oce
make -j2
sudo make install
cd $HOME/gitroot/oceBuild
make test
```

Passed all the tests. But when I tried to build heekscad some error occurred. Than I tried to install oce by the following command:

```
sudo apt-get install liboce-visualization-dev libwxgtk2.8-dev libgtkglext1-dev python-dev
```

And then tried to build heekscad again. Now I get this error, which looks different from the previous error.

```
[  1%] Building CXX object interface/CMakeFiles/heeksintf.dir/DoubleInput.cpp.o
In file included from /usr/include/oce/Standard_Integer.hxx:23:0,
                 from /usr/include/oce/Standard_Address.hxx:35,
                 from /usr/include/oce/Standard.hxx:20,
                 from /home/takeokatsuki/heekscad/src/stdafx.h:72,
                 from /home/takeokatsuki/heekscad/interface/DoubleInput.cpp:5:
/usr/include/oce/Standard_values.h:34:4: error: #error "check oce-config.h file or compilation options: OCE_HAVE_CLIMITS, OCE_HAVE_LIMITS, or OCE_HAVE_LIMITS_H should be defined"
 #  error "check oce-config.h file or compilation options: OCE_HAVE_CLIMITS, OCE_HAVE_LIMITS, or OCE_HAVE_LIMITS_H should be defined"
    ^
In file included from /usr/include/oce/Standard_OStream.hxx:22:0,
                 from /usr/include/oce/Standard_ExtCharacter.hxx:38,
                 from /usr/include/oce/Standard_PrimitiveTypes.hxx:43,
                 from /usr/include/oce/gp_TrsfForm.hxx:36,
                 from /usr/include/oce/gp_Trsf.hxx:23,
                 from /usr/include/oce/BRepAdaptor_Curve.hxx:20,
                 from /home/takeokatsuki/heekscad/src/stdafx.h:76,
                 from /home/takeokatsuki/heekscad/interface/DoubleInput.cpp:5:
/usr/include/oce/Standard_Stream.hxx:43:4: error: #error "check config.h file or compilation options: either OCE_HAVE_IOSTREAM or OCE_HAVE_IOSTREAM_H should be defined"
   #error "check config.h file or compilation options: either OCE_HAVE_IOSTREAM or OCE_HAVE_IOSTREAM_H should be defined"
    ^
In file included from /usr/include/oce/Standard_OutOfRange.hxx:19:0,
                 from /usr/include/oce/gp_Mat.lxx:16,
                 from /usr/include/oce/gp_Mat.hxx:260,
                 from /usr/include/oce/gp_Trsf.hxx:26,
                 from /usr/include/oce/BRepAdaptor_Curve.hxx:20,
                 from /home/takeokatsuki/heekscad/src/stdafx.h:76,
                 from /home/takeokatsuki/heekscad/interface/DoubleInput.cpp:5:
/usr/include/oce/Standard_SStream.hxx:35:27: fatal error: strstream.h: No such file or directory
     #include <strstream.h>
                           ^
compilation terminated.
make[2]: *** [interface/CMakeFiles/heeksintf.dir/DoubleInput.cpp.o] Error 1
make[1]: *** [interface/CMakeFiles/heeksintf.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jieter** [comment]
Hmm, strange. Unfortunately, I do not remember doing anything special when installing this. I did an update and recompile of heekscad last week and it just worked.

**Comment by tkatsuki** [comment]
If you were to install OCE again what command would you use? Just sudo apt-get install liboce-visualization-dev?

**Comment by jieter** [comment]
If I'd remember, I would tell it to you... As far as I remember, it was just an `apt-get`, nothing special.

**Comment by tkatsuki** [comment]
OK, thanks, I will try that.
By the way, the reason I am trying to build heekscnc from source is because of the issue described here (I think):
https://code.google.com/p/heekscnc/issues/detail?id=336
When I run a simple pocket operation (e.g. half-sphere dent), the G00 move to the start location in each block changes by the increment set at "step down", which ends up plunging a hole at the start location depending on the start depth and step down size. It also generates redundant passes. Do you have the same problem? Or have you managed to fix the issue in your build? To me this looks like a critical problem as a CAM and I am wondering how people who use HeeksCNC manage this.

**Comment by jieter** [comment]
hmm, is this just a pocket issue? I've no problems like this with pocketing. I never did any real 3D milling with Heekscad though.

**Comment by jieter** [comment]
BTW, I don't think you need to rebuild to change the python scripts as suggested by the 4th commment.

**Comment by tkatsuki** [comment]
Hmm, maybe I am not using the pocket operation correctly... If you run a pocket operation on this object, do you see Z2 (the one right before G01) constantly over iterations? http://wikisend.com/download/800360/test.heeks
Under my environment it changes Z2, Z1.8, Z1.6, etc.
Sorry for asking many basic questions but where are the Heeks python scripts located in Ubuntu?

**Comment by jieter** [comment]
This is what I get when pressing the 'G0` button with your file:

``````
Traceback (most recent call last):
  File "/tmp/post.py", line 9, in <module>
    import nc.attach as attach
  File "/usr/lib/heekscnc/nc/attach.py", line 8, in <module>
    import ocl
ImportError: No module named ocl```
``````

**Comment by tkatsuki** [comment]
It is a simple pocket operation with a 2mm ball end mill, but .heeks files might not be transferable? I've located the python script so I will try to modify it. Thanks so much for your time with this.

**Comment by jieter** [comment]
hmm, seems to be very buggy. The tool table is defined in the file, but it still uses my own default tooltable...
